# -*- encoding: utf-8 -*-

=begin
#Container Registry service

#Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls.

The version of the OpenAPI document: 1.0
Contact: support@cloud.ionos.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "ionoscloud-container-registry/version"

Gem::Specification.new do |s|
  s.name        = "ionoscloud-container-registry"
  s.version     = IonoscloudContainerRegistry::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@cloud.ionos.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Container Registry service Ruby Gem"
  s.description = "Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
