=begin
#Container Registry service

#Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls.

The version of the OpenAPI document: 1.0
Contact: support@cloud.ionos.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

# Common files
require 'ionoscloud-container-registry/api_client'
require 'ionoscloud-container-registry/api_error'
require 'ionoscloud-container-registry/version'
require 'ionoscloud-container-registry/configuration'

# Models
require 'ionoscloud-container-registry/models/api_error_message'
require 'ionoscloud-container-registry/models/api_error_response'
require 'ionoscloud-container-registry/models/api_resource_metadata'
require 'ionoscloud-container-registry/models/credentials'
require 'ionoscloud-container-registry/models/day'
require 'ionoscloud-container-registry/models/location'
require 'ionoscloud-container-registry/models/locations_response'
require 'ionoscloud-container-registry/models/pagination_links'
require 'ionoscloud-container-registry/models/patch_registry_input'
require 'ionoscloud-container-registry/models/patch_token_input'
require 'ionoscloud-container-registry/models/post_registry_input'
require 'ionoscloud-container-registry/models/post_registry_output'
require 'ionoscloud-container-registry/models/post_registry_properties'
require 'ionoscloud-container-registry/models/post_token_input'
require 'ionoscloud-container-registry/models/post_token_output'
require 'ionoscloud-container-registry/models/post_token_properties'
require 'ionoscloud-container-registry/models/put_registry_input'
require 'ionoscloud-container-registry/models/put_registry_output'
require 'ionoscloud-container-registry/models/put_token_input'
require 'ionoscloud-container-registry/models/put_token_output'
require 'ionoscloud-container-registry/models/registries_response'
require 'ionoscloud-container-registry/models/registry_properties'
require 'ionoscloud-container-registry/models/registry_response'
require 'ionoscloud-container-registry/models/scope'
require 'ionoscloud-container-registry/models/storage_usage'
require 'ionoscloud-container-registry/models/token_properties'
require 'ionoscloud-container-registry/models/token_response'
require 'ionoscloud-container-registry/models/tokens_response'
require 'ionoscloud-container-registry/models/weekly_schedule'

# APIs
require 'ionoscloud-container-registry/api/locations_api'
require 'ionoscloud-container-registry/api/names_api'
require 'ionoscloud-container-registry/api/registries_api'
require 'ionoscloud-container-registry/api/repositories_api'
require 'ionoscloud-container-registry/api/tokens_api'

module IonoscloudContainerRegistry
  class << self
    # Customize default settings for the SDK using block.
    #   IonoscloudContainerRegistry.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
