=begin
#Container Registry service

#Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls.

The version of the OpenAPI document: 1.0
Contact: support@cloud.ionos.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

require 'date'
require 'time'

module IonoscloudContainerRegistry
  class Day
    MONDAY = "Monday".freeze
    TUESDAY = "Tuesday".freeze
    WEDNESDAY = "Wednesday".freeze
    THURSDAY = "Thursday".freeze
    FRIDAY = "Friday".freeze
    SATURDAY = "Saturday".freeze
    SUNDAY = "Sunday".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Day.constants.select { |c| Day::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Day" if constantValues.empty?
      value
    end
  end
end
